Retrieving compiler information: Compiler using remote version: 'latest', solidity version: 0.8.19+commit.7dd6d404.Emscripten.clang TypeError: Type struct ModelVoting.Model memory is only valid in storage because it contains a (nested) mapping.   add ModelVoting.sol   --> /Users/ranxi/Library/CloudStorage/OneDrive-共享的库-onedrive/Project/Cremodeva/Smart Contract/ModelVoting.sol:27:9:    | 27 |         Model memory newModel;    |         ^^^^^^^^^^^^^^^^^^^^^
Compilation failed with 1 errors